//
// Created by javier on 3/6/20.
//

#ifndef CUCURUCHO_CONSTANTES_H
#define CUCURUCHO_CONSTANTES_H

#define PANTALLA_ANCHO 960
#define PANTALLA_ALTO 672
#define PANTALLA_ESCALA 1

#define CAMPO_ANCHO 960
#define CAMPO_ALTO 576

#define SONIDO_ACTIVADO 0


#endif //CUCURUCHO_CONSTANTES_H
