//
// Created by javier on 3/6/20.
//

#ifndef CUCURUCHO_CONSTANTES_H
#define CUCURUCHO_CONSTANTES_H

#define PANTALLA_ANCHO 960
#define PANTALLA_ALTO 672
#define PANTALLA_ESCALA 1

#define HUD_ALTO 96

#define CAMPO_ANCHO PANTALLA_ANCHO
#define CAMPO_ALTO PANTALLA_ALTO - HUD_ALTO

#define SONIDO_ACTIVADO 1
#define HELPERS_ACTIVADOS 1


#endif //CUCURUCHO_CONSTANTES_H
